[project]
name = "django-htmx-modal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django-htmx>=1.21.0",
    "django>=5.1.4",
]
